version: "3.9"
services:
  postgres:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_DB: "gomodel"
      POSTGRES_USER: "gomodel"
      POSTGRES_PASSWORD: "gomodel"
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"